package agent

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	domainAgent "github.com/mololab/alodb/internal/domain/agent"
	"github.com/mololab/alodb/internal/infrastructure/agent/response"
	"github.com/mololab/alodb/pkg/logger"

	"google.golang.org/adk/agent"
	"google.golang.org/adk/session"
	"google.golang.org/genai"
)

// Chat processes a chat request and returns a response
func (a *DBAgent) Chat(ctx context.Context, req domainAgent.ChatRequest) (*domainAgent.ChatResponse, error) {
	logger.Debug().
		Str("message", req.Message).
		Bool("has_connection", req.ConnectionString != "").
		Msg("processing chat request")

	sessionID, err := a.getOrCreateSession(ctx, req.SessionID)
	if err != nil {
		return nil, fmt.Errorf("failed to manage session: %w", err)
	}

	ctx = a.storeSecureContext(ctx, req.ConnectionString)

	responseText, err := a.runAgentToCompletion(ctx, sessionID, req.Message)
	if err != nil {
		return nil, fmt.Errorf("agent execution failed: %w", err)
	}

	logger.Debug().Str("response", truncateForLog(responseText, 100)).Msg("chat completed")

	parser := response.NewParser()
	return parser.Parse(sessionID, responseText)
}

// getOrCreateSession returns existing session ID or creates a new one
func (a *DBAgent) getOrCreateSession(ctx context.Context, existingID string) (string, error) {
	if existingID != "" {
		logger.Debug().Str("session_id", existingID).Msg("continuing session")
		if err := a.ensureSession(ctx, existingID); err != nil {
			return "", err
		}
		return existingID, nil
	}

	newID := uuid.New().String()
	logger.Debug().Str("session_id", newID).Msg("new session created")
	if err := a.ensureSession(ctx, newID); err != nil {
		return "", err
	}
	return newID, nil
}

// storeSecureContext adds secure data to context (connection string, cache TTL)
func (a *DBAgent) storeSecureContext(ctx context.Context, connStr string) context.Context {
	if connStr != "" {
		ctx = context.WithValue(ctx, connectionStringKey, connStr)
	}
	ctx = context.WithValue(ctx, schemaCacheTTLKey, a.schemaCacheTTL)
	return ctx
}

// runAgentToCompletion runs the agent and waits for the final response after all tool calls
func (a *DBAgent) runAgentToCompletion(ctx context.Context, sessionID, message string) (string, error) {
	content := genai.NewContentFromText(message, genai.RoleUser)
	events := a.runner.Run(ctx, sessionID, sessionID, content, agent.RunConfig{})

	var finalResponse string
	var lastModelResponse string
	eventCount := 0

	for event, err := range events {
		eventCount++
		if err != nil {
			logger.Error().Err(err).Msg("agent execution error")
			return "", fmt.Errorf("agent execution error: %w", err)
		}

		logEvent(event, eventCount)

		if event.Content != nil && event.Content.Role == string(genai.RoleModel) {
			text := ExtractTextFromEvent(event)
			if text != "" {
				lastModelResponse = text
			}
		}
	}

	finalResponse = lastModelResponse

	if finalResponse == "" {
		logger.Warn().Int("event_count", eventCount).Msg("no response generated")
		return "", fmt.Errorf("no response generated by agent")
	}

	logger.Debug().Int("event_count", eventCount).Msg("agent completed")
	return finalResponse, nil
}

// logEvent logs event details for debugging
func logEvent(event *session.Event, count int) {
	if event == nil || event.Content == nil {
		return
	}

	var functionName string
	var hasFunctionCall, hasFunctionResponse bool

	for _, part := range event.Content.Parts {
		if part.FunctionCall != nil {
			hasFunctionCall = true
			functionName = part.FunctionCall.Name
		}
		if part.FunctionResponse != nil {
			hasFunctionResponse = true
			functionName = part.FunctionResponse.Name
		}
	}

	if hasFunctionCall || hasFunctionResponse {
		logger.Debug().
			Int("event", count).
			Str("author", event.Author).
			Bool("func_call", hasFunctionCall).
			Bool("func_resp", hasFunctionResponse).
			Str("func", functionName).
			Msg("agent event")
	}
}

// truncateForLog truncates a string for logging purposes
func truncateForLog(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}

// ensureSession creates a session if it doesn't exist
func (a *DBAgent) ensureSession(ctx context.Context, sessionID string) error {
	_, err := a.sessionService.Get(ctx, &session.GetRequest{
		AppName:   agentName,
		UserID:    sessionID,
		SessionID: sessionID,
	})
	if err == nil {
		return nil // session exists
	}

	// create new session
	_, err = a.sessionService.Create(ctx, &session.CreateRequest{
		AppName:   agentName,
		UserID:    sessionID,
		SessionID: sessionID,
	})
	if err != nil {
		return fmt.Errorf("failed to create session: %w", err)
	}

	return nil
}
