package agent

import (
	"context"
	"fmt"
	"time"

	domainAgent "github.com/mololab/alodb/internal/domain/agent"
	"github.com/mololab/alodb/internal/domain/database"
	ws "github.com/mololab/alodb/internal/domain/websocket"
	"github.com/mololab/alodb/internal/infrastructure/agent/response"
	"github.com/mololab/alodb/internal/infrastructure/agent/schema"
	"github.com/mololab/alodb/pkg/logger"

	"google.golang.org/adk/agent"
	"google.golang.org/genai"
)

type StreamCallbacks struct {
	OnThinking         func(status string)
	OnToolCall         func(tool string)
	OnTextDelta        func(delta string)
	OnResponseComplete func(resp *domainAgent.ChatResponse)
	OnError            func(err error)
}

// StreamChat processes chat with streaming events and client-side query execution
func (a *DBAgent) StreamChat(
	ctx context.Context,
	sessionID string,
	message string,
	executor schema.QueryExecutor,
	callbacks StreamCallbacks,
) {
	logger.Debug().
		Str("session_id", sessionID).
		Str("message", truncateForLog(message, 100)).
		Msg("starting stream chat")

	if callbacks.OnThinking != nil {
		callbacks.OnThinking("started")
	}

	actualSessionID, err := a.getOrCreateSession(ctx, sessionID)
	if err != nil {
		if callbacks.OnError != nil {
			callbacks.OnError(fmt.Errorf("session error: %w", err))
		}
		return
	}

	// store query executor and schema holder in context for tool use
	ctx = context.WithValue(ctx, queryExecutorKey, executor)
	ctx = context.WithValue(ctx, schemaCacheTTLKey, a.schemaCacheTTL)
	holder := &SchemaHolder{}
	ctx = context.WithValue(ctx, schemaHolderKey, holder)

	content := genai.NewContentFromText(message, genai.RoleUser)
	events := a.runner.Run(ctx, actualSessionID, actualSessionID, content, agent.RunConfig{})

	var lastModelResponse string
	eventCount := 0

	for event, err := range events {
		eventCount++
		if err != nil {
			logger.Error().Err(err).Msg("agent execution error")
			if callbacks.OnError != nil {
				callbacks.OnError(fmt.Errorf("agent error: %w", err))
			}
			return
		}

		if event.Content != nil {
			if HasFunctionCall(event) {
				toolName := GetFunctionCallName(event)
				logger.Debug().Str("tool", toolName).Msg("tool call")
				if callbacks.OnToolCall != nil {
					callbacks.OnToolCall(toolName)
				}
				if callbacks.OnThinking != nil {
					callbacks.OnThinking("reading_schema")
				}
			}

			if event.Content.Role == string(genai.RoleModel) {
				text := ExtractTextFromEvent(event)
				if text != "" {
					lastModelResponse = text
					if callbacks.OnTextDelta != nil {
						callbacks.OnTextDelta(text)
					}
				}
			}
		}
	}

	if lastModelResponse == "" {
		logger.Warn().Int("event_count", eventCount).Msg("no response generated")
		if callbacks.OnError != nil {
			callbacks.OnError(fmt.Errorf("no response generated by agent"))
		}
		return
	}

	logger.Debug().Int("event_count", eventCount).Msg("stream chat completed")

	parser := response.NewParser()
	resp, err := parser.Parse(actualSessionID, lastModelResponse)
	if err != nil {
		if callbacks.OnError != nil {
			callbacks.OnError(err)
		}
		return
	}

	dbSchema := holder.Schema
	if dbSchema == nil {
		if cached, ok := a.schemaStore.Load(actualSessionID); ok {
			dbSchema = cached.(*database.DatabaseSchema)
			logger.Debug().Msg("using schema from session store for diagram")
		}
	} else {
		a.schemaStore.Store(actualSessionID, dbSchema)
	}

	if dbSchema != nil {
		for i := range resp.Queries {
			if len(resp.Queries[i].UsedTables) > 0 {
				resp.Queries[i].Diagram = schema.GenerateMermaid(dbSchema, resp.Queries[i].UsedTables)
			}
		}
	}

	if callbacks.OnResponseComplete != nil {
		callbacks.OnResponseComplete(resp)
	}
}

type ClientQueryExecutor struct {
	executeQuery func(name, description, query string, step, totalSteps int, timeout time.Duration) (*ws.QueryResultPayload, error)
}

func NewClientQueryExecutor(
	executeQuery func(name, description, query string, step, totalSteps int, timeout time.Duration) (*ws.QueryResultPayload, error),
) *ClientQueryExecutor {
	return &ClientQueryExecutor{executeQuery: executeQuery}
}

func (e *ClientQueryExecutor) ExecuteQuery(name, description, query string, step, totalSteps int, timeout time.Duration) (*ws.QueryResultPayload, error) {
	return e.executeQuery(name, description, query, step, totalSteps, timeout)
}

const (
	queryExecutorKey = "query_executor"
	schemaHolderKey  = "schema_holder"
)

func (a *DBAgent) getOrCreateSession(ctx context.Context, existingID string) (string, error) {
	if existingID != "" {
		logger.Debug().Str("session_id", existingID).Msg("continuing session")
		if err := a.ensureSession(ctx, existingID); err != nil {
			return "", err
		}
		return existingID, nil
	}

	newID := generateSessionID()
	logger.Debug().Str("session_id", newID).Msg("new session created")
	if err := a.ensureSession(ctx, newID); err != nil {
		return "", err
	}
	return newID, nil
}

func generateSessionID() string {
	return fmt.Sprintf("%d", time.Now().UnixNano())
}

func truncateForLog(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}
